### ISSUE TITLE
User Story: Comment on latest Poll

### ISSUE THREAD

**Issue by whelew** [whelew/My-First-Agile-Project#4]
As a **user** I can **anonymously provide extra thoughts beyond the user response to the poll** so that **I can leave a comment for the organiser of the runs before submitting my poll**.

# Acceptance Criteria:
- Provide option as a checkbox.
- Checkbox is "checked" automatically.
- Option should be next to submit button.
- After submitting default submission confirmation should include the users username. 

## Tasks:

- [ ] Design Comment Box and Checkbox.
- [ ] Design Layout of Comment Box and Checkbox.
- [ ] Create the HTML and CSS for comment box.
- [ ] Create code model for anonymity function.
